shell shouldn't die on SIGINT; quit rc on SIGQUIT; add comments
SCCS-vsn: etc/rc 5.16

diff --git a/usr/src/etc/rc b/usr/src/etc/rc
--- a/usr/src/etc/rc
+++ b/usr/src/etc/rc
@@ -1,6 +1,15 @@
 #
-#	@(#)rc	5.15 (Berkeley) %G%
+#	@(#)rc	5.16 (Berkeley) %G%
 #
+
+# System startup script run by init on autoboot
+# or after single-user.
+# Output and error are redirected to console by init,
+# and the console is the controlling terminal.
+
+# Set shell to ignore SIGINT (2), but not children;
+# shell catches SIGQUIT (3) and returns to single user after fsck.
+trap : 2
 
 HOME=/; export HOME
 PATH=/sbin:/bin:/usr/sbin:/usr/bin
@@ -8,7 +17,6 @@ export PATH
 
 if [ -r /fastboot ]
 then
-	rm -f /fastboot
 	echo Fast boot ... skipping disk checks >/dev/console
 elif [ $1x = autobootx ]
 then
@@ -21,8 +29,8 @@ then
 		exit 1
 		;;
 	4)
-		reboot -n
-		echo "reboot -n failed... help!" >/dev/console
+		reboot
+		echo "reboot failed... help!" >/dev/console
 		exit 1
 		;;
 	8)
@@ -43,6 +51,8 @@ then
 		;;
 	esac
 fi
+
+trap "echo 'Reboot interrupted'; exit 1" 3
 
 swapon -a						>/dev/console 2>&1
 
@@ -102,6 +112,7 @@ echo preserving editor files  >/dev/console
 
 echo clearing /tmp 	>/dev/console
 # prune quickly with one rm, then use find to clean up /tmp/[lq]*
+# (not needed with mfs /tmp, but doesn't hurt there...)
 (cd /tmp; rm -rf [a-km-pr-zA-Z]* )
 (cd /tmp; find . ! -name . ! -name lost+found ! -name quotas -exec rm -r {} \; )
 
